# Generated by Django 4.1.3 on 2022-11-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Pedido',
            fields=[
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('correo', models.CharField(default='', max_length=100)),
                ('Telefono', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('Cantidad_de_ejemplares', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('Inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.inventario_pedido')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='inventario_pedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.proveedor'),
        ),
    ]
